In [1]:
import os
os.chdir('..')
from ImageUtilsTools.GeneAnalysis.ahba_surf import AHBA_Prerocess_fsLR

lh_parc = 'ImageUtilsTools/GeneAnalysis/data/Glasser2016.L.32k_fs_LR.label.gii'
process = AHBA_Prerocess_fsLR(data_dir='/Users/burgerhuang/Documents/AHBA')

Preprocessing AHBA data...

INFO: Group-level atlas provided; using MNI coords for tissue samples
INFO: Reannotating probes with information from Arnatkevic̆iūtė et al., 2019, NeuroImage
INFO: Filtering probes with intensity-based threshold of 0.5
INFO: 31569 probes survive intensity-based filtering
INFO: Reducing probes indexing same gene with method: diff_stability
/opt/miniconda3/envs/imagingwork/lib/python3.8/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/opt/miniconda3/envs/imagingwork/lib/python3.8/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/opt/miniconda3/envs/imagingwork/lib/python3.8/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/opt/miniconda3/envs/imagingwork/lib/python3.8/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/opt/miniconda3/envs/imagingwork/lib/python3.8/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/opt/miniconda3/envs/imagingwork/lib/python3.8/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
INFO: 15633 genes remain after probe filtering + selection
INFO: 904 / 904 samples matched to regions for donor #9861
INFO: 845 / 845 samples matched to regions for donor #10021
INFO: 353 / 353 samples matched to regions for donor #12876
INFO: 513 / 513 samples matched to regions for donor #14380
INFO: 437 / 437 samples matched to regions for donor #15496
INFO: 414 / 414 samples matched to regions for donor #15697

AHBA data preprocessed.
Expression matrix:  (3466, 15633)
Sample information:  (3466, 22)
Removing samples more than 4mm from the surface...
Removed 1790 samples.
After removing shapes:
Expression matrix:  (1676, 15633)
Sample information:  (1676, 22)

In [2]:
lh_parc = '/Users/burgerhuang/Desktop/PhD_work/Epilepsy_downstream/template/Schaefer2018_400Parcels_7Networks_order.L.32k_fs_LR.label.gii'
rh_parc = '/Users/burgerhuang/Desktop/PhD_work/Epilepsy_downstream/template/Schaefer2018_400Parcels_7Networks_order.R.32k_fs_LR.label.gii'
process.assign_atlas_to_info(lh_parc, rh_parc)

Left hemisphere: 9 labels unassigned.
Right hemisphere: 52 labels unassigned.

,structure_id,slab_num,slab_type,structure_acronym,structure_name,polygon_id,mri_voxel_x,mri_voxel_y,mri_voxel_z,mni_x,...,reg_num,top_level,region_clean,R,A,S,vertex,mm_to_surf,hemi,atlas_label
well_id,,,,,,,,,,,,,,,,,,,,,
594,4077,22,CX,PCLa-i,"paracentral lobule, anterior part, right, infe...",37470,87,52,116,6.281693,...,4071.0,CTX,"paracentral lobule, anterior part",5.5,-26.0,44.0,4410,-1.341842,right,316.0
787,4143,14,CX,MTG-i,"middle temporal gyrus, left, inferior bank of ...",38869,145,112,83,-55.367069,...,4140.0,CTX,middle temporal gyrus,-52.5,7.0,-16.0,21630,0.163333,left,150.0
961,4273,10,CX,SIG,"short insular gyri, left",28153,127,84,57,-33.515487,...,4272.0,CTX,short insular gyri,-34.5,33.0,12.0,11031,1.093029,left,99.0
428,4092,24,CX,PoG-cs,"postcentral gyrus, right, bank of the central ...",35008,78,40,124,17.957951,...,4085.0,CTX,postcentral gyrus,14.5,-34.0,56.0,5358,-1.563552,right,264.0
969,4201,22,CX,OTG-i,"occipito-temporal gyrus, left, inferior bank o...",37564,137,116,122,-50.810163,...,4198.0,CTX,occipito-temporal gyrus,-44.5,-32.0,-20.0,22313,1.445987,left,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157772852,4023,3,CX,SFG-m,"superior frontal gyrus, left, medial bank of g...",155781929,96,56,47,-3.752821,...,4021.0,CTX,superior frontal gyrus,-6.0,44.0,53.0,29249,0.857173,left,178.0
157772980,4224,3,CX,CgGf-i,"cingulate gyrus, frontal part, left, inferior ...",155807874,95,115,49,-2.587349,...,4221.0,CTX,"cingulate gyrus, frontal part",-5.0,42.0,-6.0,28126,2.714564,left,169.0
157772932,4048,3,CX,GRe,"gyrus rectus, left",155807925,99,133,49,-7.015003,...,4047.0,CTX,gyrus rectus,-9.0,42.0,-24.0,21168,0.713217,left,116.0
157773028,4045,3,CX,orIFG,"inferior frontal gyrus, orbital part, left",155779802,140,118,47,-49.525825,...,4035.0,CTX,inferior frontal gyrus,-50.0,44.0,-9.0,11603,0.591467,left,170.0
157773012,4039,3,CX,trIFG,"inferior frontal gyrus, triangular part, left",155779801,145,102,47,-52.317688,...,4035.0,CTX,inferior frontal gyrus,-55.0,44.0,7.0,11596,0.389103,left,172.0

In [4]:
df = process.aggregate_expression()
df.head(10)

gene_symbol,A1BG,A1BG-AS1,A2M,A2ML1,A3GALT2,A4GALT,AAAS,AACS,AADACL3,AADAT,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
atlas_label,,,,,,,,,,,,,,,,,,,,,
1.0,0.577794,0.640496,0.294130,0.445932,0.503839,0.353468,0.339804,0.688194,0.589797,0.516883,...,0.387055,0.671995,0.631566,0.605015,0.452452,0.492317,0.663265,0.365163,0.622544,0.496363
2.0,0.681012,0.548179,0.343760,0.457681,0.313090,0.465951,0.376306,0.573688,0.342246,0.489134,...,0.355591,0.639359,0.708004,0.630608,0.516463,0.481341,0.540537,0.319729,0.443579,0.591818
3.0,0.688366,0.834541,0.404315,0.260291,0.395546,0.346626,0.684824,0.743979,0.332017,0.551044,...,0.604642,0.815979,0.611725,0.327259,0.409126,0.541598,0.568426,0.532303,0.430175,0.478034
4.0,0.366412,0.453478,0.417391,0.615193,0.554983,0.336459,0.557849,0.687707,0.692530,0.635962,...,0.706551,0.461055,0.533255,0.677438,0.767141,0.340906,0.633839,0.458332,0.600060,0.516030
5.0,0.507644,0.419560,0.539172,0.588483,0.349047,0.390535,0.537802,0.483871,0.344485,0.526527,...,0.432026,0.587488,0.377988,0.489545,0.430815,0.669812,0.461967,0.503695,0.686798,0.443708
6.0,0.372471,0.452557,0.418033,0.346623,0.359335,0.438873,0.711874,0.543178,0.466273,0.569815,...,0.449314,0.591972,0.535542,0.478854,0.468292,0.430860,0.625017,0.752130,0.729495,0.616240
7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8.0,0.426439,0.493708,0.471236,0.437657,0.434315,0.437782,0.604001,0.618467,0.396371,0.549110,...,0.598084,0.585576,0.493051,0.599844,0.516082,0.499452,0.573003,0.630555,0.594906,0.478727
9.0,0.253288,0.249072,0.337884,0.534712,0.361468,0.356535,0.649458,0.255322,0.512489,0.771750,...,0.746635,0.391472,0.578458,0.655370,0.621750,0.274171,0.472200,0.761750,0.814003,0.620495
10.0,0.409068,0.246050,0.605866,0.606294,0.597883,0.587864,0.587666,0.348607,0.704654,0.374880,...,0.404861,0.532895,0.374375,0.643810,0.460855,0.650874,0.316468,0.699205,0.804154,0.305405

In [ ]:
expression = process.get_expression
sample_info = process.get_sample_info

In [ ]:
import pandas as pd

donors = [9861, 10021, 12876, 14380, 15496, 15697]
donor_expression = {}
for donor in donors:
    donor_expression[donor] = expression[sample_info['brain'] == donor].groupby(
        sample_info['atlas_label']
    ).mean()

agg_expression = pd.concat(donor_expression)
agg_expression

In [ ]:
df = agg_expression.groupby('atlas_label').mean()

In [ ]:
from ImageUtilsTools.Plotting import Plot_Each_Region_Num
from neuromaps.datasets import fetch_fslr

hum_surfaces = fetch_fslr(density='32k')
hum_lh, hum_rh = hum_surfaces['veryinflated']
figure = Plot_Each_Region_Num(df.index, lh_parc, hum_lh, vmin=0, vmax=1)

In [ ]:
regions = df.index
regions.to_numpy()

In [ ]:
import numpy as np
all_regions = range(1, 201)
missing_regions = np.setdiff1d(all_regions, regions)
missing_regions

In [ ]:
figure = Plot_Each_Region_Num(missing_regions, lh_parc, hum_lh)